version: "3.8"
services:
  nestjs: 
    restart: always #if it fails then this will restart it
    build: . #looks in current directory for a docker file
    ports:
      - ${NESTJS_PORT}:3000
    links:
      - mongo
  mongodb:
    image : mongo
    container_name: mongodb
    ports:
      - ${MONGO_PORT}:27017
