version: "3.8"
services:
  app: 
    container_name: docker-node-mongo
    restart: always #if it fails then this will restart it
    build: . #looks in current directory for a docker file
    ports:
      - '80:3000'
    links:
      - mongo
  mongodb:
    image : mongo
    container_name: mongodb
    ports:
      - '27017:27017'
